source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'FPIGListKitModule_Example' do
  pod 'FPIGListKitModule', :path => '../'
  pod 'FPRefresh'
  pod 'Masonry'
  pod 'SDWebImage'

  target 'FPIGListKitModule_Tests' do
    inherit! :search_paths

    
  end
end
