use_frameworks!

platform :ios, '8.0'

target 'FPIGListKitModule_Example' do
  pod 'FPIGListKitModule', :path => '../'

  target 'FPIGListKitModule_Tests' do
    inherit! :search_paths

    
  end
end
